### ISSUE TITLE
Incorrect url for Amazon Linux

### ISSUE THREAD

**Issue by yoshiwaan** [chef-cookbooks/yum-chef#1]
Hi,

When using amazon linux the version is set incorrectly in the Chef repo url path:

https://packagecloud.io/chef/stable/el/2015/x86_64

This is because the versions for amazon linux are not the same as EL, so the current latest version of amazon linux is 2015.03 and the previous is 2014.09.

This might have to be statically set to match EL6 for now, as that is what amazon linux is currently based on.

This is the culprit in default/attributes.rb:
```
yum['baseurl'] = "https://packagecloud.io/chef/stable/el/#{node['platform_version'].split('.').first}/$basearch"
```

**Comment by jtimberman** [comment]
You'll need to modify the attribute in a wrapper cookbook, role, or similar. Please be aware that Amazon Linux is not [a supported platform](https://docs.chef.io/supported_platforms.html) - for Chef Server or the addons or products (Manage, Reporting, Analytics, etc). We don't plan to add direct support for Amazon Linux to this cookbook.
