### ISSUE TITLE
Yum base_url needs to be revised

### ISSUE THREAD

**Issue by echandradhas** [chef-cookbooks/yum-chef#9]
I noticed that yum['baseurl']        = "https://packagecloud.io/chef/stable/el/ 
 is now 
https://packagecloud.io/chef/stable/packages/el/6/chef-server-core-12.4.1-1.el6.x86_64.rpm.
Can you please revise it. It is breaking installs.

**Comment by iennae** [comment]
@echandradhas, where are you seeing that your baseurl is defined as mentioned? The cookbook as is defines it as   yum['baseurl']        = "https://packagecloud.io/chef/stable/el/#{node['platform_version'].split('.').first}/$basearch". It's an attribute so can be set as needed based on your environment. 

Thanks! Looking forward to getting this working as expected for you.

**Comment by iennae** [comment]
It's been updated to use the current package location as of PR #10 and PR #11 cookbook 1.0.1. If you are still having problems, please reopen with more information.

Thank you!
